---
apiVersion: v1
kind: Namespace
metadata:
  name: node-taint-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-taint-manager

  name: node-taint-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-taint-manager
  template:
    metadata:
      labels:
        app: node-taint-manager
    spec:
      containers:
      - name: node-taint-manager
        image: node-taint-manager:latest
        imagePullPolicy: Never
      serviceAccount: node-taint-manager
      tolerations:
      - operator: "Exists"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: node-taint-manager
  name: node-taint-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-taint-manager
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "list"
  - "patch"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-taint-manager
roleRef:
  kind: ClusterRole
  name: node-taint-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: node-taint-manager
  namespace: node-taint-manager
